### ISSUE TITLE
Export data to local MQTT

### ISSUE THREAD

**Issue by jxlarrea** [rabits/ha-ef-ble#1]
This is great stuff.  I have been trying to get data from my SHP2 and DPU locally for a while now. Unfortunately I have zero knowledge of Python. 

Would you consider creating something that would export all the data to a local MQTT server? Most people do not have their Home Assistant server nowhere near where the SHP2 is physically located.

**Comment by rabits** [comment]
Hi @jxlarrea , I see it could be useful - but this integration is strictly about supporting BLE EcoFlow devices for HA. Maybe there is someone can help you to use https://github.com/rabits/ef-ble-reverse scripts to convert the received data from BLE to MQTT without a need of HA. Since I have not much expertise or time to do so - I would leave it to someone who can. You can try to find someone from MQTT world on HA forums for example, but quite sure they will need to have their time compensated.
